[env:esp32]
platform = espressif32@6.9.0
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.flash_size = 4MB
board_build.cmake_extra_args =
    -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.esp32"
build_flags =
    -DAPP_VERSION=\"1.0.0\"
